embed_dim: 64
hidden_size: 128
layer_num: 2
head_num: 2
#dropout: 0.1 #0.2
dropout: 0.2
activation: 'gelu'
#negative_count: 20
negative_count: 1
layer_norm_eps: 1e-12

#mask_ratio: 0.1 #0.2
mask_ratio: 0.2
steal: False
pooling_type: 'mask'
gpu: [1]
weight_decay: 1e-5

cutoff: 10 #10
